### ISSUE TITLE
Redirect from a disabled default petstore url

### ISSUE THREAD

**Issue by levindev7** [springdoc/springdoc-openapi#812] opened 2020-08-02 21:30 UTC
I know that to disable the default petstore url, i need to use the property - 
"springdoc.swagger-ui.disable-swagger-default-url=true"
but after that, when using the address of the default page localhost:8080/swagger-ui/**index.html**, I see a page with a message
"**No API definition provided**.", which is not the best solution for my clients, can I somehow make a redirect from this address or configure getting some HTTP status 4xx ?

**Comment by bnasslahsen** [comment] 2020-08-03 09:38
@levindev7, 

 This is a duplicate of #763.
 You can simply override SwaggerIndexPageTransformer, to have any page you would prefer.

**Closed by bnasslahsen** 2020-08-03 09:38 UTC
