### ISSUE TITLE
swagger-config is loaded twice

### ISSUE THREAD

**Issue by lrozenblyum** [springdoc/springdoc-openapi#688] opened 2020-05-26 07:15 UTC
**Describe the bug**
swagger-config url is loaded twice.
Thus onComplete callback is also called twice which makes it harder to customize the UI.

**To Reproduce**
springdoc-openapi 1.3.9

You may check the online demo: 
https://springdoc-openapi-test-app1-exhausted-civet.eu-de.mybluemix.net/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

**Expected behavior**
- swagger-config should be loaded just once

**Screenshots**
![image](https://user-images.githubusercontent.com/1285898/82871111-b3664e00-9f39-11ea-9bef-0526e05778da.png)

**Comment by bnasslahsen** [comment] 2020-05-26 08:34
@lrozenblyum, 

 Duplicate of #349,  #545.
 This is a bug on the swagger-ui, not in the springdoc-openapi:
https://github.com/swagger-api/swagger-ui/issues/4825

**Closed** 2020-05-26 08:34 UTC

**Comment by bnasslahsen** [comment] 2020-06-07 16:29
@lrozenblyum, 

 Starting from v1.4.1, the following properties can be used to prevent the load of the swagger-config twice. 
 Please note this properties works only in the case where there is no groups (no multiple urls and no configUrl set on the swagger-ui):

- If your REST APIs, are not using OAuth2:
```properties
springdoc.swagger-ui.display-query-params-without-oauth2=true
```

- If your REST APIs, are using OAuth2:
```properties
springdoc.swagger-ui.display-query-params=true
```

**Comment by lrozenblyum** [comment] 2020-06-09 06:46
Thanks for sharing! @bnasslahsen 
As a matter of fact we're using groups (for versioning of API)...
