### ISSUE TITLE
Attribute schema of header does not appear in openapi(json & yaml) generated file

### ISSUE THREAD

**Issue by YDanot** [springdoc/springdoc-openapi#1116] opened 2021-03-24 10:34 UTC
**Describe the bug**
- My generated openapi.yaml is not valid, this is caused by the absence of schema in a header of an api-response. 

**To Reproduce**
- What version of spring-boot you are using 
  - 2.3.9-RELEASE
- What modules and versions of springdoc-openapi are you using:
  - springdoc-openapi-ui
  - springdoc-openapi-security
  - springdoc-openapi-kotlin
- What is the actual and the expected result using OpenAPI Description (yml or json)?
  - actual  
  `responses:
        "201":
          description: Successful operation
          headers:
            Location:
              description: Link to the created resource
              style: simple`
  - expected
  `responses:
        "201":
          description: Successful operation
          headers:
            Location:
              description: Link to the created resource
              style: simple
              schema: 
                type: string`

- This is produced by these annotations on a simple post: 
`    @ApiResponses(
        value = [ApiResponse(
            responseCode = "201", description = "Successful operation",
            headers = arrayOf(Header(name = HttpHeaders.LOCATION, description = "Link to the created resource", schema = Schema(implementation = String::class)))
        )]
    )`

**Comment by bnasslahsen** [comment] 2021-03-24 18:06
This is duplicate of https://github.com/springdoc/springdoc-openapi/issues/103
You have workaround for it. 
Waiting for the swagger-core team to plan a fix for it..

**Closed by bnasslahsen** 2021-03-24 18:06 UTC
