### ISSUE TITLE
Parameters annotated with @ParameterObject cannot be set to optional

### ISSUE THREAD

**Issue by lkshrk** [springdoc/springdoc-openapi#542] opened 2020-04-06 09:50 UTC
Query Parameters annotated with `@ParameterObject` cannot be set to Optional.

**Controller**
```
@RestController
public class SampleRestController {
    @GetMapping(value = "/api/endpoint")
    public SampleResponse getSample(@ParameterObject QueryParams queryParams) {
        return apiService.getSample(queryParams);
    }
}
```

**Model**
```
public class QueryParams {
    @Parameter(description = "An example for an optional parameter", required = false)
    private String iAmNotRequired;    
}
```

All provided options in the `@Parameter` annotation should be applied to the respective field.

**Comment by bnasslahsen** [comment] 2020-04-06 11:38
You can use this workaround, on the attributes of you object:
```java
	@Nullable
	@Parameter(description = "string parameter")
	private String stringParam;
```
Or
```java
	@Parameter(description = "string parameter")
	private Optional<String> stringParam;
```
This is almost a duplicate of #541

**Closed by bnasslahsen** 2020-04-06 11:38 UTC
