### ISSUE TITLE
Custom operation filters

### ISSUE THREAD

**Issue by romash1408** [springdoc/springdoc-openapi#1025] opened 2021-01-19 08:52 UTC
**Is your feature request related to a problem? Please describe.**
We have little library for api versioning that generates custom RequestCondition depending on special annotation. So we can write controllers like this:
```java
@RestController
public class Controller {
    @Versioner(till = 0)
    @GetMapping("/test")
    public String old() {
        return "old";
    }

    @Versioner(from = 1)
    @GetMapping("/test")
    public Integer other() {
        return 123;
    }
}
```
Then `GET /v0/test` returns `"old"`  and `GET /v1/test` returns `123`

Now we need openapi to produce 2 groups: group `v0` with `GET /test` endpoint that produces `String` and group `v1` with `GET /test` endpoint that produces `Integer`

**Describe the solution you'd like**
Something like `addCustomFilter` in `GroupedOpenApi.Builder` where I can use `handlerMethod.getMethodAnnotation(Versioner.class)` to determine, if this method should be displayed in this group

**Describe alternatives you've considered**
- I have tried to filter paths in `OpenApiCustomiser`, but when it is called, there is already only one endpoint because the others have been overwritten [here](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L402) due to identical `operationPath` (`/test`)

**Comment by bnasslahsen** [comment] 2021-01-19 18:38
@romash1408, 

 You can combine `GroupedOpenApi` with `OperationCustomizer` where you have access to `handlerMethod`.
 This is [sample code](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app68/SpringDocTestApp.java).

**Comment by romash1408** [comment] 2021-01-20 02:51
Hello, @bnasslahsen. thank you for you response.
Maybe my issue description is not very good, sorry. But I need to **remove** (what I called "_to filter_") some operations. And as I can see `OperationCustomizer` doesn't have methods to do that. Am I wrong?

**Comment by romash1408** [comment] 2021-01-20 03:09
By the way, `OperationCustomizer`'s javadoc says that it should [`@return customized operation`](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/customizers/OperationCustomizer.java#L40), but returned value is [ignored](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L706).
This behavior may confuse people who try
```java
	OperationCustomizer operationCustomizer() {
		return (Operation operation, HandlerMethod handlerMethod) -> {
                        Operation newOperation = new Operation();
                        // ...
			return newOperation;
		};
	}
```

**Comment by bnasslahsen** [comment] 2021-01-20 09:26
@romash1408, 

 OperationCustomizer is not for filtering operations.
 For deciding whether to hide or not operation. You can simply use `@Hidden` annotation.

**Comment by romash1408** [comment] 2021-01-20 17:08
`@Hidden` annotation don't let me filter operation only in certain groups. I need to select operations for group depending on my custom annotation.

**Comment by bnasslahsen** [comment] 2021-01-20 17:45
@romash1408, 

 Frankly, i am not sure you need any addtional feature. 
 I don't understand why you are not able to filter using `OpenApiCustomiser` as mentioned earlier.

**Comment by michaelkrog** [comment] 2021-07-30 11:36
@romash1408 Did you find a solution for this?

I have been trying for 2 days now to make springdoc filter out the right controllers for the specific (version) groups but havent succeeded yet. It always seem to have merged methods from multiple versioned controllers into the same operations before I can get to them with OpenApiCustomizer because they have the same path and signature.

**Comment by bnasslahsen** [comment] 2021-07-31 10:38
@michaelkrog, 

What criteria are you using to identify a controller for the specific (version)  ?

**Comment by michaelkrog** [comment] 2021-08-01 06:24
I have a custom Annotation on the controllerlevel. A custom RequestMappingHandlerMapping & RequrstCondition ensures that all versions of the same controller can be registered with the otherwise same MVC signature. In my case only a header determines the required version of the controller to hit.

I tried a lot of the examples I could find and several of your suggestions for filtering out in groups, but I always ended up with mixed results, fx. multiple versions of the same schema being referenced in one group. It seems to me that the controller methods that have the same MVC signature (not including my custom conditions) are merged before I can customize them.

**Comment by bnasslahsen** [comment] 2021-08-01 09:08
@michaelkrog, 

If you are in case you using headers that determines the required version, you can use `headersToMatch` of `GroupedOpenApi`. Sample code is available [here](https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app134).

**Comment by michaelkrog** [comment] 2021-08-02 09:55
@bnasslahsen 

Simply using Spring MVC's header matching won't suffice in my case. My need for selecting the controller to serve the request is more sophisticated.

I have created the smallest project reproducing the problem that I can think of here:
https://github.com/michaelkrog/springdoc-demo

The Readme of the project adds a bit more details to the versioning concept and problem I am seeing.

Do you want a whole new issue created or is it fine to reopen this one if you find it to be an issue?

**Comment by bnasslahsen** [comment] 2021-08-02 21:09
@michaelkrog, 

You are having a very custom version logic.
Anyway, for the sample you have mentioned, you can still work it out using the combination of `packagesToScan` and `packagesToExclude`:

```java
@Bean
public GroupedOpenApi groupV1OpenApi() {
	return GroupedOpenApi.builder()
			.group("V20210101").packagesToScan("com.example.demo")
			.packagesToExclude("com.example.demo.dated.v20200101")
			.build();
}

@Bean
public GroupedOpenApi groupV2OpenApi() {
	return GroupedOpenApi.builder()
			.group("V20200101").packagesToScan("com.example.demo.dated.v20200101.controllers")
			.build();
}
```

**Closed by bnasslahsen** 2021-08-02 21:09 UTC
