### ISSUE TITLE
Unrecognized parameter between upgrades

### ISSUE THREAD

**Issue by knyttl** [springdoc/springdoc-openapi#2036] opened 2023-01-12 07:55 UTC
**Describe the bug**

It is now hard to go back and find out the difference in dependencies, but it seems that springdoc is now unable to recognize parameter names:

1. version before:
<img width="1316" alt="Screenshot 2023-01-12 at 8 50 17" src="https://user-images.githubusercontent.com/401107/212008908-e555e0bf-56cd-4076-8047-bb47f531a37a.png">

2. version now:
<img width="897" alt="Screenshot 2023-01-12 at 8 49 55" src="https://user-images.githubusercontent.com/401107/212008976-186a4533-48bd-49e8-ac25-13c3277a3a12.png">

I am afraid I will not be able to go back in history and test every single upgraded dependency, so I would like to ask if there is a way to debug this? Can I search for something in logs?

**Current versions**
- Spring: 6.0.3
- Kotlin: 1.8.0
- SpringDoc:
    - org.springdoc:springdoc-openapi-starter-common:2.0.2
    - org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2

**Expected behavior**

All the parameters should be named.

**Comment by bnasslahsen** [comment] 2023-02-04 22:06
duplicate of #2028

**Closed** 2023-02-04 22:06 UTC
Labels: duplicate
