### ISSUE TITLE
Upgrade to spring-cloud-function 4.2.0

### ISSUE THREAD

**Issue by ratoaq2** [springdoc/springdoc-openapi#2829] opened 2024-12-20 10:25 UTC
This is a simple feature request that I'm kindly asking (if possible):

To upgrade spring-cloud-function to its final version: 4.2.0 and do a new minor springdoc-openapi release.

Latest release has a dependency to a "non-final" version: spring-cloud-function 4.2.0-M1
This is an optional dependency and usually that doesn't cause major issues.
But for some maven plugins and inside an environment with no access to repositories with "non-final" versions, this can cause issues. Bellow is just an example of such issue:

```
08:19:45  [ERROR] Failed to execute goal com.lazerycode.jmeter:jmeter-maven-plugin:3.8.0:configure (configuration) on project <redacted-project-name>: Failed to collect dependencies at org.springdoc:springdoc-openapi-starter-common:jar:2.7.0 -> org.springframework.cloud:spring-cloud-function-web:jar:4.2.0-M1: Failed to read artifact descriptor for org.springframework.cloud:spring-cloud-function-web:jar:4.2.0-M1: The following artifacts could not be resolved: io.micrometer:micrometer-bom:pom:1.14.0-M1 (absent): Could not find artifact io.micrometer:micrometer-bom:pom:1.14.0-M1 in <redacted-artifactory-name> (http://artifactory:8081/artifactory/maven) -> [Help 1]
08:19:45  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.lazerycode.jmeter:jmeter-maven-plugin:3.8.0:configure (configuration) on project <redacted-project-name>: Failed to collect dependencies at org.springdoc:springdoc-openapi-starter-common:jar:2.7.0 -> org.springframework.cloud:spring-cloud-function-web:jar:4.2.0-M1
```

**Comment by bnasslahsen** [comment] 2024-12-28 13:40
@ratoaq2,

This is duplicate of  #2804
We have to wait for spring-cloud-function 4.2.1 release.

**Closed by bnasslahsen** 2024-12-28 13:40 UTC
