### ISSUE TITLE
Since 1.3.5 /v3/api-docs cannot be found anymore

### ISSUE THREAD

**Issue by sticksen** [springdoc/springdoc-openapi#643] opened 2020-05-04 13:58 UTC
**Describe the bug**
I updated from 1.3.4 to 1.3.5 without changing anything else and Swagger UI does not work anymore:
![Screenshot 2020-05-04 at 15 54 14](https://user-images.githubusercontent.com/2657113/80973340-85e92180-8e1f-11ea-8ec7-4598cc3b9621.png)

**To Reproduce**
- What version of spring-boot you are using? 2.2.6.RELEASE
- What modules and versions of springdoc-openapi are you using? before: implementation("org.springdoc:springdoc-openapi-ui:1.3.4") and 1.3.5 after
- What is the actual and the expected result using OpenAPI Description (yml or json)?
Actual: missing. Expected: filled with at least something :)
- Provide with a sample code (HelloController) or Test that reproduces the problem
Sorry, don´t have this, but I´ve seen an error that is maybe related:
```
com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: io.swagger.v3.oas.models.OpenAPI["paths"]->io.swagger.v3.oas.models.Paths["/v1/devices"]->io.swagger.v3.oas.models.PathItem["get"]->io.swagger.v3.oas.models.Operation["responses"]->io.swagger.v3.oas.models.responses.ApiResponses["null"])
```

**Expected behavior**
The /v3/api-docs should be found again

**Screenshots**
see above

**Comment by bnasslahsen** [comment] 2020-05-04 14:05
Can you do 2 things:
 - test with v1.3.7
 
If its the same result. Please add then sample code to reproduce.

**Comment by lrozenblyum** [comment] 2020-05-04 14:07
Might be duplicate of https://github.com/springdoc/springdoc-openapi/issues/630

**Comment by sticksen** [comment] 2020-05-04 14:14
1.3.7 does not fix it.
Yes, #630 is the exact same problem. Example code is inside of #630.

**Comment by bnasslahsen** [comment] 2020-05-04 14:15
#630 is fixed.
Can you please test with the latest Snapshot ?

**Comment by sticksen** [comment] 2020-05-04 14:23
I´m happy to test as soon as 1.3.8 is available. Seems like the commit just didn´t make it into 1.3.7.
Fine for me, I can wait for 1.3.8. Thanks everybody!

**Comment by bnasslahsen** [comment] 2020-05-04 17:09
Might be duplicate of #630.
Unable to reproduce with the sample code provided.

Can be valdated with v1.3.8 released today.
The ticket can be reopened, if the relevant information to reproduce the issue are provided.

**Closed by bnasslahsen** 2020-05-04 17:09 UTC
