### ISSUE TITLE
1.5.10 update to 1.5.11, cause error

### ISSUE THREAD

**Issue by NickZhang1024** [springdoc/springdoc-openapi#1293] opened 2021-10-11 00:36 UTC
version 1.5.10 is fine, update to 1.5.11, cause error:

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 3 of method swaggerWelcome in org.springdoc.webmvc.ui.SwaggerConfig required a single bean, but 2 were found:
        - requestMappingHandlerMapping: defined by method 'requestMappingHandlerMapping' in class path resource [org/springframework/web/servlet/config/annotation/DelegatingWebMvcConfiguration.class]
        - oauth2EndpointHandlerMapping: defined by method 'oauth2EndpointHandlerMapping' in class path resource [org/springframework/security/oauth2/config/annotation/web/configuration/AuthorizationServerEndpointsConfiguration.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

**Comment by bnasslahsen** [comment] 2021-10-11 06:22
@NickZhang1024 , 

Duplicate of https://github.com/springdoc/springdoc-openapi/issues/1288

Stick with v1.5.10, if you are having this issue.
This one will be solved for the next release.

**Closed by bnasslahsen** 2021-10-11 06:22 UTC
