### ISSUE TITLE
Support Spring property resolution on Parameter level

### ISSUE THREAD

**Issue by laurinpascal** [springdoc/springdoc-openapi#475] opened 2020-03-05 12:08 UTC
Hi,
when switching from springfox to springdoc, I found out that springdoc only supports spring property resolution with swagger-annotations on `@Operation` level as stated [here](https://springdoc.github.io/springdoc-openapi-demos/faq.html#can-i-use-spring-property-with-swagger-annotations). It would be nice, if spring properties could also be resolved on `@Parameter` level. 

Example: `@Parameter(description = "${my.spring.property}")`

Thank you!

**Comment by bnasslahsen** [comment] 2020-03-05 19:41
Duplicate of #463 .
Fixed by #464.

**Closed by bnasslahsen** 2020-03-05 19:41 UTC
