### ISSUE TITLE
"😱 Could not render n, see the console." since version 1.4.5

### ISSUE THREAD

**Issue by schneivo77** [springdoc/springdoc-openapi#875] opened 2020-09-21 15:00 UTC
**Describe the bug**
In version 1.4.5 and 1.4.6 I get the error "😱 Could not render n, see the console." in the "Responses" field on every request I execute from the Swagger-UI.
In version 1.4.4 everything is working fine.

**To Reproduce**
I'm using `spring-boot-starter-parent` on version `2.3.4.RELEASE` with only the `springdoc-openapi-ui` module.

**Screenshots**

**The error on the UI:**
![image](https://user-images.githubusercontent.com/9406058/93782375-ca3c5900-fc2a-11ea-9937-240c9ac18bcf.png)

**The output I get in Chrome Console, after pressing the "Execute" button:**
![image](https://user-images.githubusercontent.com/9406058/93782541-fd7ee800-fc2a-11ea-90dd-285a3ad713c7.png)

**Comment by bnasslahsen** [comment] 2020-09-21 15:06
@schneivo77, 

 It's a duplicate of #872 which is already resolved.

**Closed by bnasslahsen** 2020-09-21 15:06 UTC

**Comment by schneivo77** [comment] 2020-09-21 15:11
Oh, OK. Thanks for the quick response!
