### ISSUE TITLE
Multiple RequestBodies as inner classes with the same name will lead to only one being recognized

### ISSUE THREAD

**Issue by khbnr** [springdoc/springdoc-openapi#652] opened 2020-05-06 14:38 UTC
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough
I'm defining POJOs being used as RequestBody for Spring Controller methods in inner classes of the controller classes they are being used in. When two of theses POJOs in different controller classes are having the same name, springdoc will only recognize the first one (alphabetically by parent class name) and show it also as the request body for the other controllers. 

**To Reproduce**
- What version of spring-boot you are using? 2.2.6.RELEASE
- What modules and versions of springdoc-openapi are you using? org.springdoc:springdoc-openapi-ui:1.3.9

- What is the actual and the expected result using OpenAPI Description (yml or json)?
Actual:
`openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /hello:
    post:
      tags:
      - hello-controller
      operationId: hello
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /world:
    post:
      tags:
      - world-controller
      operationId: hello_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Request:
      type: object
      properties:
        greeting:
          type: string
`

expected: I don't really know how I would prefer to deal with this properly. But I would've at leasted expected an exception to be thrown, that there can't be two schemas with the same name in the Open API spec instead of silently dropping some of these. 
I don't know if it would make sense to take the parent's class name into account here

- Provide with a sample code (HelloController) or Test that reproduces the problem
`package org.example;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {

    @PostMapping(value = "/hello")
    public String hello(@RequestBody Request request) {
        return request.greeting + " World";
    }

    static class Request {

        private String greeting;

        public Request() {
        }

        public Request(String greeting) {
            this.greeting = greeting;
        }

        public String getGreeting() {
            return greeting;
        }

        public void setGreeting(String greeting) {
            this.greeting = greeting;
        }
    }
}
`

`package org.example;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class WorldController {

    @PostMapping(value = "/world")
    public String hello(@RequestBody Request request) {
        return "Hello " + request.world;
    }

    static class Request {

        private String world;

        public Request() {
        }

        public Request(final String world) {
            this.world = world;
        }

        public String getGreeting() {
            return world;
        }

        public void setGreeting(final String greeting) {
            this.world = greeting;
        }
    }
}
`

**Expected behavior**
- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?
Please see "What is the actual and the expected result using OpenAPI Description (yml or json)?"

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment] 2020-05-06 16:59
hI @khbnr, 

  This is a duplicate of https://github.com/springdoc/springdoc-openapi/issues/554.
 Its already resolved by the swagger team: https://github.com/springdoc/springdoc-openapi/issues/548.

 If you can not wait their fix, you can have a look at this guide how to generate FQNs:
  - https://dzone.com/articles/doing-more-with-springdoc-openapi

**Closed by bnasslahsen** 2020-05-06 16:59 UTC
