### ISSUE TITLE
Regression in 1.2.1 - An attempt was made to call a method that does not exist.

### ISSUE THREAD

**Issue by ucraida** [springdoc/springdoc-openapi#139] opened 2019-11-03 03:26 UTC
Edit - occurs if project has springboot 2.1.x, upgrading to 2.2.0 resolves it. 

1.2.0 loads fine, 1.2.1 and later fail on springboot startup with this error:

```

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.data.AbstractRepositoryConfigurationSourceSupport$AutoConfiguredAnnotationRepositoryConfigurationSource.<init>(AbstractRepositoryConfigurationSourceSupport.java:128)

The following method did not exist:

    org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource.<init>(Lorg/springframework/core/type/AnnotationMetadata;Ljava/lang/Class;Lorg/springframework/core/io/ResourceLoader;Lorg/springframework/core/env/Environment;Lorg/springframework/beans/factory/support/BeanDefinitionRegistry;Lorg/springframework/beans/factory/support/BeanNameGenerator;)V

The method's class, org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource, is available from the following locations:

    jar:file:/Users/username/.gradle/caches/modules-2/files-2.1/org.springframework.data/spring-data-commons/2.1.5.RELEASE/851578f7a47dc3ec6dce071c2688ab3987439142/spring-data-commons-2.1.5.RELEASE.jar!/org/springframework/data/repository/config/AnnotationRepositoryConfigurationSource.class

It was loaded from the following location:

    file:/Users/username/.gradle/caches/modules-2/files-2.1/org.springframework.data/spring-data-commons/2.1.5.RELEASE/851578f7a47dc3ec6dce071c2688ab3987439142/spring-data-commons-2.1.5.RELEASE.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.data.repository.config.AnnotationRepositoryConfigurationSource

Disconnected from the target VM, address: '127.0.0.1:64638', transport: 'socket'

Process finished with exit code 1
```

**Comment by springdoc** [comment] 2019-11-03 09:33
Hi,

The regression, you mention is not reproducible with the demo applications, even while downgrading the versions of springbok-openapi and spring-boot.
Your error, seems to be related to spring-data (jars configuration). We don't have any usage of it in our library.
Could you please first, review your application dependencies first.

 If it's not the case, you add the reference to a sample code to reproduce the issue, so we can identify the root cause?

**Comment by springdoc** [comment] 2019-11-04 22:12
Hi @ucraida, 

I am closing this issue for now, as there are no elements to confirm it or reproduce it.
If you can answer my previous message, and you provide the necessary elements to investigate, I will reopen it.

**Closed by springdoc** 2019-11-04 22:12 UTC
