### ISSUE TITLE
Kotlin Support ?

### ISSUE THREAD

**Issue by DavidRomao** [springdoc/springdoc-openapi#269] opened 2019-12-14 22:41 UTC
When generating the documentation It is not marking non nullable types as required. As I was not able to any information if kotlin is supported, I would like to know if kotlin is not supported or am I missing something? 

I could not get the fields to show up as required with @Nonnull or @Schema(required=true) as well.

**Comment by joaodias14** [comment] 2019-12-14 23:35
Kotlin is supported, but to my knowledge, there is no special rule for non-nullable Kotlin types. This means that `@RequestParam` is the one influencing the fact that a given variable is required or not.
The following works as expected:
`suspend fun keys(@PathVariable redisInstance: RedisInstance, @RequestParam(required = false) test: String?)`

**Comment by DavidRomao** [comment] 2019-12-14 23:54
I am actually referring to the object used with @RequestBody, not a paremeter. Sorry I should have been more specific.  I wanted to set the field of a class as required. 

I expected this to work but It didn't mark the field as required.
`data class RegisterUserDTO(
                           @Schema(required=true)
                           val email: String,
                           @Schema(required=true)
                           val password: String,
                           @Schema(required=true)
                           val name: String
)
fun register(@RequestBody user : RegisterUserDTO )
`

**Comment by joaodias14** [comment] 2019-12-15 00:11
Oh sorry, I thought you were talking about query parameters.
To make that work, you must use `@field:Schema` instead of `@Schema`. You must use this `field:` prefix if you define classes via constructor declaration and want to apply a given annotation to one of the attributes. Take a look at https://kotlinlang.org/docs/reference/annotations.html#annotation-use-site-targets.

**Comment by springdoc** [comment] 2019-12-15 10:03
Thank you @joaodias14  for the support.

**Comment by WtfJoke** [comment] 2019-12-19 14:26
Hi there

A follow up question, we have kind of a similar issue.

We have following classes:

```kotlin
data class RegistrationForm(
    @field:Schema(required = true) val businessName: String,
    @field:Schema(required = true) val address: Address,
)

data class Address(
    @field:Schema(required = true) val street: String,
    @field:Schema(required = true) val streetNumber: String,
    @field:Schema(required = true) val postCode: String,
    @field:Schema(required = true) val city: String
)
```

Setting the required property works for all fields, except for the address field - see the attached screenshot of the swagger ui
![swaggerregistrationform](https://user-images.githubusercontent.com/7139697/71181068-b581fd80-2273-11ea-8680-a68424c372d3.PNG)

Do you have an idea what could cause this and how to fix it? Thanks in advance

**Comment by joaodias14** [comment] 2019-12-19 16:51
Hi @WtfJoke, can you please provide the corresponding api-docs?
But my guess is that this is a Swagger UI issue.

**Comment by WtfJoke** [comment] 2019-12-19 17:29
```json  
"RegistrationForm": {
        "required": [
          "businessName"
        ],
        "type": "object",
        "properties": {
          "businessName": {
            "type": "string"
          },
          "address": {
            "$ref": "#/components/schemas/Address"
          }
}
```

Shorted api-docs looks like this. As you can see only businessName is marked as required and address not. 

Its not Swagger-UI issue since we generate Typescript/Kotlin-Code out of swagger and its marked as Nullable/Not required.

**Comment by joaodias14** [comment] 2019-12-21 20:13
Hi @WtfJoke, this is a Swagger issue --> https://github.com/swagger-api/swagger-core/issues/3259.
It seems there is a hacky solution if you really need it --> https://stackoverflow.com/questions/51671883/swagger-ignores-schema-properties-for-referenced-schemas.

**Comment by WtfJoke** [comment] 2019-12-22 11:02
Thanks @joaodias14, I actually wanted to try the requiredProperties after christmas to check if the same problem occurs. Couldnt imagine that its a swagger issue.

**Comment by springdoc** [comment] 2019-12-22 17:44
Thank you guys. After these discussions, we can close this issue.
And if required by @WtfJoke feedback, it can be reopened

**Closed by springdoc** 2019-12-22 17:44 UTC

**Comment by glockbender** [comment] 2019-12-27 14:42
> Hi @WtfJoke, this is a Swagger issue --> [swagger-api/swagger-core#3259](https://github.com/swagger-api/swagger-core/issues/3259).
> It seems there is a hacky solution if you really need it --> https://stackoverflow.com/questions/51671883/swagger-ignores-schema-properties-for-referenced-schemas.

Another solution - using javax.validation.NotNull annotation

**Comment by WtfJoke** [comment] 2020-01-02 08:44
Just wanted to let you know, that replacing `@field:Schema(required = true)` on field level replacing with `@Schema(requiredProperties = ["businessName", "address"])` on class-level works as intended:

![grafik](https://user-images.githubusercontent.com/7139697/71658400-31844700-2d44-11ea-901f-8b1d05192b4e.png)

Thanks for your help guys!

**Comment by VedavyasBhatJupiter** [comment] 2020-02-10 12:07
@joaodias14 Using `@field:Schema(required = true)` on every non-nullable field in model classes makes the model look very verbose. Can I automate this? Can I configure this in the `OpenAPI` bean? What I'd like to do is for every class having a non-nullable field, the generated yaml would have the required field. Looks like it might be possible if I use `OpenAPI.components`, but the `Schema` object does not hold the class information.

**Comment by joaodias14** [comment] 2020-02-10 19:56
Hi @VedavyasBhatJupiter, I don't really know the inner workings of the model classes processing. But I would say that most probably there is the need to add this behaviour to springdoc so that a not nullable kotlin attribute is considered required without the need of any annotation.
Feel free to contribute with your proposal of implementation.

**Comment by joaodias14** [comment] 2020-02-11 11:42
Hi again @VedavyasBhatJupiter, it seems that there is already a PR that might just do what you need --> https://github.com/springdoc/springdoc-openapi/pull/413.

**Comment by VedavyasBhatJupiter** [comment] 2020-02-11 12:16
Hey @joaodias14 , the PR has been closed (and is by a colleague of mine). That won't work because the Kotlin annotation does not have runtime retention so it won't be read by springdoc-openapi
