### ISSUE TITLE
Spring Boot WebFlux 3.0.3 results in the hostname "0:0:0:0:0:0:0:1"

### ISSUE THREAD

**Issue by davidmelia** [springdoc/springdoc-openapi#2090] opened 2023-02-23 20:30 UTC
**Describe the bug**

After upgrading from Spring Boot WebFlux 3.0.2 to Spring Boot WebFlux 3.0.3 I am getting an odd hostname:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/8583712/221022281-96becb12-a519-46cf-8679-5858a17ca5f9.png">

**To Reproduce**
I have a super simple spring boot 3.0.3 project in https://github.com/davidmelia/open-api-issues-hostname

Navigating to http://localhost:8080/webjars/swagger-ui/index.html#/home-controller/home you can see the odd hostname

**Expected behavior**

if you downgrade to boot 3.0.2 in the pom you get the usual hostname:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/8583712/221022574-b253146e-69ce-40cc-b0f3-2e881228e20c.png">

**Comment by programista-zacny** [comment] 2023-02-23 21:01
I have the same problem but I reproduce it a little bit different.

My properties:
```
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
```

When I open url `http://127.0.0.1:8080/api-docs` everything is working fine.
When I try `http://localhost:8080/api-docs` I have an error:
```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 1 in: "0]"
```
Temurin JDK17, URLDecoder.java:235, param `String s` -> `http://[0:0:0:0:0:0:0:1%0]:8080/api-docs`
I'm using newest up-to-date Linux Manjaro.

**Comment by JohnNiang** [comment] 2023-02-24 09:06
This might be caused by <https://github.com/spring-projects/spring-framework/commit/5847454aa47644c3633a3b1dc121a593e413640e>.

**Comment by aperusset** [comment] 2023-03-01 08:48
Hi everyone !

I have exactly the same issue with Spring Boot 3.0.3, running on Ubuntu 20.04.5 LTS  Additionnaly, it causes some issues with actuator/prometheus, as the URLs are shown in my browser with IPV6 localhost resolving : 

```json
{
"_links": {
"self": {
"href": "http://[0:0:0:0:0:0:0:1%250]:9321/metrics",
"templated": false
},
"prometheus": {
"href": "http://[0:0:0:0:0:0:0:1%250]:9321/metrics/prometheus",
"templated": false
},
"health": {
"href": "http://[0:0:0:0:0:0:0:1%250]:9321/metrics/health",
"templated": false
},
"health-path": {
"href": "[http://[0:0:0:0:0:0:0:1%250]:9321/metrics/health/{*path}](http://[0:0:0:0:0:0:0:1%250]:9321/metrics/health/%7B*path%7D)",
"templated": true
}
}
}
```

I was able to quick fix this by adding these properties to my `application.yml` file : 

```yaml
server.address: 127.0.0.1
management.server.address: 127.0.0.1
```
Another solution is too add a command line argument to the JVM : `-Djava.net.preferIPv4Stack=true`

Does anyone openend an issue to Spring Framework repository or find a "real" fix ?

**Comment by JohnNiang** [comment] 2023-03-06 15:28
Just upgrade [Spring Boot 3.0.4](https://github.com/spring-projects/spring-boot/releases/tag/v3.0.4) to solve this problem.

![image](https://user-images.githubusercontent.com/16865714/223154782-e284de63-bb26-4190-a091-e6688fdbfd23.png)

**Comment by bnasslahsen** [comment] 2023-03-08 12:48
spring-boot 3.0.4 resolves this issue!

**Closed by bnasslahsen** 2023-03-08 12:48 UTC
