### ISSUE TITLE
Support sealed interfaces 

### ISSUE THREAD

**Issue by ghilainm** [springdoc/springdoc-openapi#2529] opened 2024-03-14 14:57 UTC
**Is your feature request related to a problem? Please describe.**

One of my type is defined as a sealed interface, the interface type is converted to type 'object' in the generated Open API specification.

**Describe the solution you'd like**

I would like the sealed interface to be converted to a type in specifications making use of the `oneOf` to combine the different concrete types sealed by my interface.

**Comment by codespearhead** [comment] 2024-03-19 18:32
Possible duplicate of #1558

**Comment by bnasslahsen** [comment] 2024-03-27 10:49
duplicate of #2027

**Closed** 2024-03-27 10:49 UTC
