### ISSUE TITLE
1.6.1: Setting show-actuator:true hides all other paths 

### ISSUE THREAD

**Issue by arjunchhabra-invitae** [springdoc/springdoc-openapi#1398] opened 2021-12-20 14:21 UTC
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough
On v1.6.0 (and 1.6.1), setting "show-actuator:true" is hiding all other paths on the Swagger UI.

**To Reproduce**
- What version of spring-boot you are using?
- 1.6.1
- What modules and versions of springdoc-openapi are you using?
- springdoc-openapi-ui, springdoc-openapi-kotlin, springdoc-openapi-data-rest, springdoc-openapi-javadoc
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- All paths should be shown, only actuator endpoints are show. Disabling "show-actuator:true" returns all our endpoints (but not Actuator ones, obviously)
- Provide with a sample code (HelloController) or Test that reproduces the problem

build.gradle.kts
```
    implementation("org.springdoc:springdoc-openapi-ui:1.6.1")
    implementation("org.springdoc:springdoc-openapi-kotlin:1.6.1")
    implementation("org.springdoc:springdoc-openapi-data-rest:1.6.1")
    implementation("org.springdoc:springdoc-openapi-javadoc:1.6.1")
```

application.yml
```
# OpenAPI
springdoc:
  show-actuator: true
  swagger-ui.use-root-path: true
  default-produces-media-type: application/json
```

**Additional context**
This worked fine on 1.5.3 but stopped working with 1.6.0, we thought it would be fixed with 1.6.1 but are seeing the same issue. Any advice would be appreciated! Thank you!

**Comment by bnasslahsen** [comment] 2021-12-20 16:05
@arjunchhabra-invitae, 

Seems to be duplicate of  #1381. `v1.6.1 `should fix it...
Have you tested using `v1.6.2` as well [(Demos are working just fine) ](http://158.101.191.70:8081/)?

We advise you to use the last available release before opening tickets.

If you are still facing issues,[ Provide a Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem

**Closed by bnasslahsen** 2021-12-20 16:05 UTC

**Comment by arjunchhabra-invitae** [comment] 2021-12-20 16:22
Hi @bnasslahsen , I am still seeing the issue in 1.6.1 and in 1.6.2. I will work on creating a reproducible example and upload it here. Thanks!

**Comment by bnasslahsen** [comment] 2021-12-20 16:31
@arjunchhabra-invitae, 

Sure the ticket will be reopened, once you provide the reproducible example !
