### ISSUE TITLE
Does not support Spring Data Rest

### ISSUE THREAD

**Issue by SamD** [springdoc/springdoc-openapi#126] opened 2019-10-25 04:09 UTC
Unable to reopen https://github.com/springdoc/springdoc-openapi/issues/125 so creating another

The documentation from https://github.com/springdoc/springdoc-openapi says
```
This library supports:

OpenAPI 3
Spring-boot (v1 and v2)
JSR-303, specifically for @NotNull, @Min, @Max, and @Size.
Swagger-ui
Oauth 2
```

SDR is part of Spring Boot 1 & 2 , the comment

> Spring Data Rest is not a priority.

Doesn't seem to be the case here

By not supporting SDR you are basically saying to the majority of developers don't bother with SDR and stick with MVC and BTW don't trust us with any further updates to SDR

**Comment by Stexxen** [comment] 2019-10-25 08:22
You seem to think this has been written by Spring/Pivotal etc.
**It has not**. This is a great 3rd party library, that does it's job well.
If you want hypermedia support, why not submit a PR and add it yourself.

**Comment by springdoc** [comment] 2019-10-27 09:06
Duplicate of #125 
Will be deleted.

**Closed by springdoc** 2019-10-27 09:06 UTC
