### ISSUE TITLE
Ability to disable swagger-ui default petstore url

### ISSUE THREAD

**Issue by alfonz19** [springdoc/springdoc-openapi#714] opened 2020-06-07 08:27 UTC
We are deploying to production environment. If someone opens default swagger page without configUrl specified, it's completely NOT ok, to display some playground petstore app.

by setting property(<contextPath> is placeholder):

    springdoc.swagger-ui.configUrl=/<contextPath>/v3/api-docs

I'd expect that this configUrl will be opened if configUrl is not present in URL, however it seems, that if I put this configuration here, I won't be able to use url:

    http://localhost:8080/<contextPath>/swagger-ui/index.html?configUrl=/<contextPath>/v3/api-docs

and will get PetStore undesirable even for this URL. Either I'm misreading documentation or this is a bug.

Regardless of that — I understand, that this behavior goes back to swagger_ui and their targetting of their product for non-prod environment. The web/stackoverflow/... provides examples how to block this behavior, but the suggestions are rather ridiculous(rebuilding swagger), or not appliable (because requires javascript customization of swagger). Can you suggest correct solution? I don't want to see any possibility to reach PetStore nonsense or any other config other than what we provided on our URL. If someone wants to use PetStore app, he can surely do it elsewhere. Currently we have to do it via spring resource transformer just to force swagger to good behavior.

**Comment by bnasslahsen** [comment] 2020-06-07 11:32
@alfonz19, 

 This behaviour is not related directly to sprindoc-openapi, but to swagger-ui project:
- https://github.com/swagger-api/swagger-ui/issues/6019
- https://github.com/swagger-api/swagger-ui/issues/5710

 It is a duplicate of:  #43, #379 and #660.

 Our goal is not to change the behaviour of the swagger-ui. But to build on top of it.
 I see that there is a lot of demand on disabling this default url, because its understandable from a security perspective that some organisations don't want to serve the default swagger-ui petstore url.

So waiting for the swagger-ui to address issue, we can add a property to disable it on the springdoc side, and hide all the additional configuration of adding spring resource transformer.

**Comment by alfonz19** [comment] 2020-06-07 11:42
Ok, so there is currently no way, how to correctly block it somehow from your side? 

What we probably will endup using is setting  `springdoc.swagger-ui.layout` to BaseLayout (which seems not to be the default values as your documentation says, since wihout it I'm getting StandaloneLayout) and filtering requests to overwrite all incorrect swagger requests(like removing layout or chagning configuration) to correct one. It's very bad solution, but I'm not aware of any better. Are you?

And how do you explain described behavior of configUrl?
springdoc.swagger-ui.configUrl

**Closed** 2020-06-07 12:55 UTC

**Comment by bnasslahsen** [comment] 2020-06-07 13:04
Starting from the next release v1.4.1, the following property will be added to disable the swagger-ui default petstore url:

```properties
springdoc.swagger-ui.disable-swagger-default-url=true
```

@alfonz19, you can validate it with the latest snapshot which is already deployed.

**Comment by alfonz19** [comment] 2020-06-07 19:41
Thank you very much!

**Comment by alfonz19** [comment] 2020-06-07 20:13
Tested it, it works. Thanks again.

**Comment by sourabhparsekar** [comment] 2020-10-14 08:46
springdoc.swagger-ui.disable-swagger-default-url=true

THis is not working for me in 1.4.4 version :(

**Comment by bnasslahsen** [comment] 2020-10-14 09:55
@sourabhparsekar, 

 It's just deployed using the last stable version (v1.4.8) without any issue: You can see the petstore url is disabled here:
 - http://158.101.164.60:8081/swagger-ui/index.html

 If you have having any difficulties,  you can have a look at the sample configuration for this sample:
- https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webmvc

 If you are still facing problems, please help to speed up problem diagnosis by providing as much information as possible, by providing a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) - with HelloController that reproduces the problem:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by sourabhparsekar** [comment] 2020-10-14 10:34
@bnasslahsen - Yes, after changing to v1.4.8, it works as expected. 👍

**Comment by Gungrave223** [comment] 2021-02-12 19:12
I'm new to SpringDoc and Swagger-UI. 

How do i get my api doc to show by default after disabling the pet store doc? I currently have to search /v3/api-docs in the explorer in order to get to the correct api docs.

**Comment by ilanr1** [comment] 2021-02-28 20:41
springdoc.swagger-ui.disable-swagger-default-url=true
Not working on version 1.5.4 !!!

**Comment by ak185489** [comment] 2021-03-09 08:07
I am using the spring-doc-ui version -1.5.5 and added the property (springdoc.swagger-ui.disable-swagger-default-url=true) to disable the petstore URL. Its not working for me.

**Comment by RyanHolstien** [comment] 2021-03-12 20:44
Same, changing to 1.4.8 version in the same project correctly prevents the default page from loading.

**Comment by RyanHolstien** [comment] 2021-04-14 19:40
Checked back to see if this had been fixed, it looks like it has not. Checking through the history it looks like this fix just got removed with this commit: https://github.com/springdoc/springdoc-openapi/commit/d828bdd13c5ca9397d7215a5f7f23e908d4e872d#diff-268bc5ee4a811f42ba5eff09d31ad2bba87f58fcd888d95f8d1892aa7cf0cde3

In springdoc-openapi-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerIndexTransformer.java this commit removed the line that got added that overwrites the default URL. I'll open a ticket for it
