### ISSUE TITLE
springdoc.swagger-ui.supportedSubmitMethods doesn't work

### ISSUE THREAD

**Issue by cah-renan-ferreira** [springdoc/springdoc-openapi#2770] opened 2024-10-29 15:20 UTC
I'm adding **springdoc.swagger-ui.supported-submit-methods=get,put** to my project.
Expectation is to not have the Try It Out button for other methods, but they are present anyway.

![image](https://github.com/user-attachments/assets/63ea96ab-07bb-4a8b-8f50-a7faf5f6c4af)

Spring boot version: 3.2.x
Springdoc version 2.6.x

**Comment by cah-renan-ferreira** [comment] 2024-10-30 13:56
Just confirmed that downgrade to version 2.2.0 works fine

**Comment by bnasslahsen** [comment] 2024-11-06 21:36
duplicate of Swagger-ui ignores property springdoc.swagger-ui.supported-submit-methods #2740

**Closed by bnasslahsen** 2024-11-06 21:36 UTC
