### ISSUE TITLE
Servers from cached OpenAPI are overwritten and customizer is skipped

### ISSUE THREAD

**Issue by edudar** [springdoc/springdoc-openapi#1353] opened 2021-11-30 21:47 UTC
I have an OpenAPI customizer that appends a special path suffix to server URLs. It works fine and shows proper values in UI in "Servers" dropdown. Upon page refresh, dropdown values reset to un-customized ones.

Spring Boot 2.5.7
SpringDoc 1.5.12

The problem is in `AbstractOpenApiResource.getOpenApi()` function. When it loads for the first time, there's no cached `OpenAPI` instance so full initialization goes through and runs 
```
openApiCustomisers.ifPresent(apiCustomisers -> 
  apiCustomisers.forEach(openApiCustomiser -> 
    openApiCustomiser.customise(openApi)));
```
On a subsequent reload however, there's a cached version and the code goes straight into 
```
openApi = openAPIService.updateServers(openAPIService.getCachedOpenAPI());
```
that overrides correct, customized servers with a new "generated" version and does not run any customization.

I don't know why would it be needed to overwrite servers in cached OpenAPI but if that's indeed required, I'd expect customization to be applied again. Otherwise `/api-docs` returns different responses on the first vs further calls.

Workaround: disable cache but load times increase depending on the complexity of your project.

**Comment by bnasslahsen** [comment] 2021-12-01 10:59
@edudar, 

Even the cache is enabled, the expected behavior is that the `servers.url` property generated in openapi spec, for each incoming request will be based on request's x-forwarded-* headers and not only the first load.

For overriding the servers using openApiCustomiser, this is a duplicate of #1188 and #1260.
There was regression since `v1.5.7` and fixed with [v1.5.11](https://github.com/springdoc/springdoc-openapi/releases/tag/v1.5.11)

Overriding servers using `openApiCustomiser`, it should be now possible: And this is a sample test that shows you how to implement it. 

https://github.com/springdoc/springdoc-openapi/blob/d8fbf32cc7c7331f841b83f77d816551eef218a0/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app162/OpenApiConfig.java#L11-L24

Make sure when you log issue to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
Note: For next time, make sure you log issues after testing with the last stable release (for example today: `v1.5.13`)

All these steps are mentioned in the [contribution guidelines](https://github.com/springdoc/springdoc-openapi/blob/d8fbf32cc7c7331f841b83f77d816551eef218a0/CONTRIBUTING.adoc).

This ticket will be closed and can be reopened if you update it with any relevant information as described in the [contribution guidelines](https://github.com/springdoc/springdoc-openapi/blob/d8fbf32cc7c7331f841b83f77d816551eef218a0/CONTRIBUTING.adoc).

**Closed by bnasslahsen** 2021-12-01 10:59 UTC

**Comment by edudar** [comment] 2021-12-01 17:18
@bnasslahsen I specified that I'm using springdoc `1.5.12` which was **the latest** when I was doing testing. `1.5.13` was released an hour before I filed this ticket and it was not propagated everywhere. 

Here's a minimal example: https://github.com/edudar/springdoc-1353

**Comment by bnasslahsen** [comment] 2021-12-01 19:11
@edudar, 

I see the cause of your error, related to the fact that you are modifying the existing Server instances.
The workaround, until the next release without disabling the cache, is you create a new server instance, as shown in the sample test.
