### ISSUE TITLE
Inconsistent swagger generation on multiple hits

### ISSUE THREAD

**Issue by patips34** [springdoc/springdoc-openapi#100] opened 2019-09-27 16:16 UTC
On error, I want to return no content from my API. I am trying to achieve like this (Picked up example from the demo), I have added 'content' to 400 as Void.class:

`@Operation(summary = "Find pet by ID", description = "Returns a single pet", security = {
			@SecurityRequirement(name = "api_key") }, tags = { "pet" })
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "successful operation", content = @Content(schema = @Schema(implementation = Pet.class))),
			@ApiResponse(responseCode = "400", description = "Invalid ID supplied", content = @Content(schema = @Schema(implementation = Void.class))),
		
	default ResponseEntity<Pet> getPetById(
			@Parameter(description = "ID of pet to return", required = true) @PathVariable("petId") Long petId) {
		return getDelegate().getPetById(petId);
	}
`

In First Hit, it shows: Empty response for 400 response code.
If you hit swagger endpoint again, it will start showing up the Pet body again as response to 400.

**Comment by springdoc** [comment] 2019-09-28 17:37
This issue is duplicate of #96.

**Closed by springdoc** 2019-09-28 17:37 UTC
Labels: duplicate
