### ISSUE TITLE
Incorrect representation of Sort property and SortObject in openapi after update to Spring Boot 3

### ISSUE THREAD

**Issue by mathsiv** [springdoc/springdoc-openapi#2763] opened 2024-10-14 08:27 UTC
I found a mismatch between the result of a call and the openapi documentation generated. The call should return a Page of MyDto, which contains a sort property. 

Environment:
- Spring Boot Version: 3.3.2
springdoc-openapi Modules:
- springdoc-openapi-starter-webmvc-ui 2.6.0
- springdoc-openapi-maven-plugin 1.4

Here is an example of response i get with my call. No sorting is applied :

```
{
  "totalElements": 49,
  "totalPages": 1,
  "size": 50,
  "content": [],
  "number": 0,
  "sort": {
    "empty": true,
    "unsorted": true,
    "sorted": false
  },
  "pageable": {
    "pageNumber": 0,
    "pageSize": 50,
    "sort": {
      "empty": true,
      "unsorted": true,
      "sorted": false
    },
    "offset": 0,
    "unpaged": false,
    "paged": true
  },
  "first": true,
  "last": true,
  "numberOfElements": 49,
  "empty": false
}

``` 

As you can see, the sort property contains an object with empty, unosrted and sorted. But my openapi documentation tells me i should get something like this :

```
PageableObject:
  type: object
  properties:
    offset:
      type: integer
      format: int64
    sort:
      type: array
      items:
        $ref: "#/components/schemas/SortObject"
    pageSize:
      type: integer
      format: int32
    pageNumber:
      type: integer
      format: int32
    paged:
      type: boolean
    unpaged:
      type: boolean

SortObject:
  type: object
  properties:
    direction:
      type: string
    nullHandling:
      type: string
    ascending:
      type: boolean
    property:
      type: string
    ignoreCase:
      type: boolean
``` 

Pretty different. My openapi swagger used to also have the 3 properties empty, unsorted and sorted when I had spring boot 2 instead of 3 (I used springdoc-openapi-ui 1.6.11 and springdoc-openapi-maven-plugin 1.1), but then changed to this. I can't figure out why.

Expected :
I'd like my openapi documentation to actually reflect the object my call responds. 

Could you help me figure out what i can do to fix this ? 

Additional info :
While looking for a solution, i found [this issue](https://github.com/springdoc/springdoc-openapi/issues/2447). It seems highly similar to mine.

**Comment by bnasslahsen** [comment] 2024-10-14 22:36
@mathsiv, 

This is duplicate of https://github.com/springdoc/springdoc-openapi/issues/2725

That should be fixed with the next release v2.7.0

**Closed by bnasslahsen** 2024-10-14 22:36 UTC
