### ISSUE TITLE
Response entity content generation error

### ISSUE THREAD

**Issue by x-carrier** [springdoc/springdoc-openapi#2537] opened 2024-03-18 04:53 UTC
**Describe the bug**

I wrote a small demo with two interfaces, a generic return entity, and two business entities, and when I used springdoc to record the two interfaces, I found that the response entities generated for the two interfaces were the same, not the actual interface response entities, and then when I tried to write more interfaces and business entities, I find that all interfaces generate the same swagger document response entities, which really bothers me

**To Reproduce**

- What version of spring-boot you are using?  3.2.1
- What modules and versions of springdoc-openapi are you using? 2.4.0
- What is the actual and the expected result using OpenAPI Description (yml or json)? json
- Provide with a sample code (HelloController) or Test that reproduces the problem 
https://github.com/x-carrier/springdoc-bug-demo/

![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/3a8d7813-160a-4ac4-878f-26feefa2857e)
![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/adcfb651-88f9-4430-9fb3-637a69c19b3c)
![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/1f3de484-184a-4d77-961f-2e322b0735c4)
![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/37430342-64fb-4c30-8521-6709fdffcafe)
![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/acd73b07-2f7a-4bea-b5d6-c7cf31827181)
![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/2489c8b8-0782-4d8f-9a30-27ffdc95957e)
![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/c6d00488-e2fb-4917-b367-a0524d4bf735)

**Comment by codespearhead** [comment] 2024-03-19 19:08
Possible duplicate of #1558

**Comment by x-carrier** [comment] 2024-03-24 14:11
> Possible duplicate of #1558

I tried to modify the entity class to remove implements Serializable, but I still got the same wrong result, and the new code was committed to the repository
Could you please tell me how to do it correctly😢

![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/d327dc7b-887d-4006-8e36-6351207755a4)
![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/e9268636-768d-4f11-8ff1-992e9ce294bc)
![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/9e1ba7b9-213c-4af5-a58d-989966df2de3)
![image](https://github.com/springdoc/springdoc-openapi/assets/49521216/bc637804-441a-4e8c-8cc4-038bbb1f7ff5)

**Comment by bnasslahsen** [comment] 2024-03-28 01:09
@x-carrier,

The problem come from your unique name:

```
@Schema(name = "Result",description = "Common Result")
public class Result<T>  {
```

Remove the `@Schema`, and you will get the correct responses

**Closed by bnasslahsen** 2024-03-28 01:09 UTC

**Comment by banterCZ** [comment] 2024-03-28 06:24
> Remove the `@Schema`, and you will get the correct responses

@bnasslahsen I do not think so. We use generic objects without `@Schema` and observe the same wrong example after upgrading from 2.3.0 to 2.4.0

- https://github.com/wultra/lime-java-core/blob/develop/rest-model-base/src/main/java/io/getlime/core/rest/model/base/response/ObjectResponse.java#L33
- https://github.com/wultra/powerauth-server/blob/develop/powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/controller/AssertionController.java#L108

<img width="1458" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/1705996/e54810b1-08fb-4039-baf8-bcfe52d2862c">

**Comment by bnasslahsen** [comment] 2024-03-28 09:14
@banterCZ,

The initial issue root cause is explained. 
If you have any other problems, make sure you follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/e8f5f12494d622bcb4a012692d3c20ea778030bc/CONTRIBUTING.adoc)
