### ISSUE TITLE
Inheritance/Polymorfism issue

### ISSUE THREAD

**Issue by MissedSte4k** [springdoc/springdoc-openapi#1572] opened 2022-03-23 10:29 UTC
Sorry for instant create/closed, accidentally pressed enter too much.

I've been [trying](https://github.com/springdoc/springdoc-openapi/issues/1558) to notify about the issue regarding polymorfism. I read, that openapi is useing swagger at it's base so let's use [this ](https://github.com/swagger-api/swagger-core/issues/3046) as an example. I already contacted them and it is working on their end. 

Let's take this code for an example:

```
package com.neurotec.sentiveillance.vms.service.web.rs.controllers;
import io.swagger.v3.oas.annotations.media.DiscriminatorMapping;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Random;

@RestController
@Tag(name = "pets")
@SecurityRequirement(name = "oauth2Security")
@RequestMapping("/upload")
public class DiscriminatorResource {

	@GetMapping("/random")
	public Pet random() {
		Random rand = new Random();

		if (rand.nextBoolean())
			return new Cat(rand.nextBoolean());
		else
			return new Dog(rand.nextBoolean());
	}

	@Schema(
			type = "object",
			title = "Pet",
			subTypes = {Cat.class, Dog.class},
			discriminatorMapping = {
					@DiscriminatorMapping(value = "CAT", schema = Cat.class),
					@DiscriminatorMapping(value = "DOG", schema = Dog.class)
			},
			discriminatorProperty = "petTypeAsString"
	)
	static class Pet {

		public enum PetType {
			CAT,
			DOG;
		}

		@Schema(required = true)
		public PetType petType;

		@Schema(required = true)
		public String petTypeAsString;

		public Pet() {
		}

		public Pet(PetType petType) {
			this.petType = petType;
			this.petTypeAsString = petType.name();
		}

	}

	static class Cat extends Pet {
		public boolean hunts;

		public Cat() {
			super(Pet.PetType.CAT);
		}

		public Cat(boolean hunts) {
			this();
			this.hunts = hunts;
		}
	}

	static class Dog extends Pet {
		public boolean barks;

		public Dog() {
			super(Pet.PetType.DOG);
		}

		public Dog(boolean barks) {
			this();
			this.barks = barks;
		}

	}
}

```

It's the same code used in swagger, just edited a bit to be more similar to the one I'm useing in my project. The expected result for endpoint /random as shown in example is this:

```
  /upload/random:
    get:
      operationId: random
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
``` 

But the actual result is this:

```
"/upload/random": {
            "get": {
                "tags": [
                    "pets"
                ],
                "operationId": "random",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "$ref": "#/components/schemas/Pet"
                                        },
                                        {
                                            "$ref": "#/components/schemas/Cat"
                                        },
                                        {
                                            "$ref": "#/components/schemas/Dog"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "oauth2Security": []
                    }
                ]
            }
        },

```

We got some additional data due to security and what not, but the problem is clear - polymorphism uses oneOf instead of parent class.

My system currently uses 
springdoc-openapi-webmvc-core 1.6.6
springdoc-openapi-security 1.6.6

Some time before we used:
springdoc-openapi-webmvc-core 1.2.29
springdoc-openapi-security 1.2.29

And it was working as intended.
Don't know if version is just correlation or causation, because we can't revert it in our project to test (crashes the app)

**Comment by bnasslahsen** [comment] 2022-03-23 19:41
@MissedSte4k, 

This looks to be a duplicate of https://github.com/springdoc/springdoc-openapi/issues/1334
Simply, use the following property and you will get the expected result:

```properties
springdoc.model-converters.polymorphic-converter.enabled=false
```

**Closed by bnasslahsen** 2022-03-23 19:41 UTC
