### ISSUE TITLE
Missing custom example for operationsSorter and tagsSorter

### ISSUE THREAD

**Issue by CarlosOnline** [springdoc/springdoc-openapi#2730] opened 2024-09-27 16:57 UTC
I scanned the internet and can't find any examples of using custom `opertationsSorter`.

Can you please provide an example of a custom `opertationsSorter` function for Spring Boot Java?

What arguments are passed to the `opertationsSorter` ?

**Comment by bnasslahsen** [comment] 2024-09-28 10:28
This duplicate of https://github.com/springdoc/springdoc-openapi/issues/1335

This example test of `opertationsSorter`, that you can use properties:
https://github.com/springdoc/springdoc-openapi/blob/0287e836c425823c3102607bc8c698ca9cb38102/springdoc-openapi-starter-webmvc-ui/src/test/java/test/org/springdoc/ui/app27/SpringDocApp27Test.java#L30-L48

If you need to declare a JS function, you can have a look [how to inject custom JS code from Java](https://github.com/springdoc/springdoc-openapi/blob/main/springdoc-openapi-starter-common/src/main/java/org/springdoc/ui/AbstractSwaggerIndexTransformer.java).

After `window.ui = SwaggerUIBundle`, you can add your customer functions.

**Closed by bnasslahsen** 2024-09-28 10:28 UTC
Labels: duplicate
