### ISSUE TITLE
Controller advice documents ApiResponse on every operation, even if the operation does not annotate the exception to be thrown

### ISSUE THREAD

**Issue by testersen** [springdoc/springdoc-openapi#2483] opened 2024-01-14 17:26 UTC
**Describe the bug**

Exception handlers annotated with `@ApiResponse` and `@ResponseStatus` seem to be applied to all operations, even if the implementing operation method handler does not throw the exception handled by the exception handler.

**To Reproduce**

- spring-boot: 3.2.1
- `org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0`
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

```kt
data class HelloResponse(val value: String)

@RestController
class HelloController {
  @GetMapping("/hello")
  @Operation(operationId = "hello", summary = "Hello, World!")
  fun hello() = HelloResponse("World")

  @GetMapping("/greet/{name}")
  @Operation(operation = "greet", summary = "Hello someone!")
  @Throws(InvalidNameException::class)
  fun greet(@PathVariable name: String) = throw InvalidNameException("Name '$name' is invalid!")
}

@ControllerAdvice
class HelloAdvisor {
  @ExceptionHandler(InvalidNameException::class)
  @ResponseStatus(HttpStatus.BAD_REQUEST)
  @ApiResponse(description = "The provided name is invalid", useReturnScheme = true)
  fun handleNameException(e: InvalidNameException): MyErrorResponse {
    TODO()
  }
}
```

**Expected behavior**

I would expect only the greeting operation to be documented with the invalid name exception, but the hello exception is also documented with it.

**Comment by iosonopersia** [comment] 2024-02-02 16:32
I have the same problem

**Comment by bnasslahsen** [comment] 2024-03-11 16:36
@iosonopersia and @testersen,

I have added a fix for this request.
You can validate it already based on the [Latest SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot)

**Closed** 2024-03-11 16:36 UTC

**Comment by iosonopersia** [comment] 2024-03-12 10:21
@bnasslahsen I can confirm you that, by using version `2.3.1-SNAPSHOT`, the problem is completely gone and everything seems to work as expected. Thank you for the effort, looking forward to the release of version `2.3.1`!

**Comment by testersen** [comment] 2024-03-12 12:08
Good work @bnasslahsen, look forward to see it hit 2.3.1! :)
