### ISSUE TITLE
Swagger / openapi definition doesn't honor `spring.jackson.property-naming-strategy` property

### ISSUE THREAD

**Issue by ZeeD** [springdoc/springdoc-openapi#2381] opened 2023-09-18 15:46 UTC
**Describe the bug**

In my project I have a bunch of entities exposed via spring data rest.
I have not set any custom jsonmapper, but I've set
`spring.jackson.property-naming-strategy = SNAKE_CASE` in my `application.properties`

however in the swagger ui / openapi json I see the field in the camelCase style (like in the java source code)

**To Reproduce**

- What version of spring-boot you are using?
3.1.3
- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-starter-webmvc-ui 2.2.0
- What is the actual and the expected result using OpenAPI Description (yml or json)?
the field names in the jsons are snake case
- Provide with a sample code (HelloController) or Test that reproduces the problem
```java
@Getter
@Setter
@Entity
public class Foo {
    private @Id @GeneratedValue Long id;
    private String barBaz;
}
```
```java
@RepositoryRestResource
@CrossOrigin
public interface FooRepository extends ListCrudRepository<Foo, Long> {
}
```

**Expected behavior**

- A clear and concise description of what you expected to happen.
I see reference to `bar_baz` in the swagger UI / openapi json
- What is the expected result using OpenAPI Description (yml or json)?
```json
...
  "components": {
      "EntityModelUser": {
        "type": "object",
        "properties": {
...
          "bar_baz": {
            "type": "string"
          }
...
```

**Screenshots**

**Additional context**
FWIW I've found a workaround setting (re-setting?) manually the "standard" jackson `ObjectMapper` to the swagger `ModelResolver`... I just don't get why do I need to set it manually

```java

@Configuration
public class OpenApiJacksonConfig {
    @Bean
    ModelResolver modelResolver(final ObjectMapper objectMapper) {
        return new ModelResolver(objectMapper);
    }
}
```

**Comment by ZeeD** [comment] 2023-09-19 11:22
On https://gist.github.com/ZeeD/860d15f68783f93daaade75078018b87 I've create a bare minimum project.
if you run it, then call `curl -s http://localhost:8080/foos/1 | jq .` you'll see 
```json
{
  "bar_baz": "qux",
  "_links": {
    "self": {
      "href": "http://localhost:8080/foos/1"
    },
    "foo": {
      "href": "http://localhost:8080/foos/1"
    }
  }
}
```
but `curl -s http://localhost:8080/v3/api-docs | jq .components.schemas.EntityModelFoo.properties` returns
```json
{
  "barBaz": {
    "type": "string"
  },
  "_links": {
    "$ref": "#/components/schemas/Links"
  }
}
```

**Comment by bnasslahsen** [comment] 2023-12-02 15:23
This is a duplicate of https://github.com/springdoc/springdoc-openapi/issues/66

**Closed by bnasslahsen** 2023-12-02 15:23 UTC
