### ISSUE TITLE
2.6.0 of springdoc-openapi-starter-webmvc-ui seems to introduce a regression when using @JsonUnwrapped & @Delegate

### ISSUE THREAD

**Issue by NPE78** [springdoc/springdoc-openapi#2682] opened 2024-08-21 07:36 UTC
**Describe the bug**

We are using models encapsulated with `@JsonUnwrapped` and `@Delegate` (from lombok) instead of using regular `extends` (favor composition over inheritance).

Before version 2.6.0 of springdoc-openapi-starter-webmvc-ui, we were using 2.5.0 (we're using renovatebot to ensure we're at the latest versions).

All the fields from the delegated model are missing.

**To Reproduce**

- What version of spring-boot you are using?
3.3.2

- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-starter-webmvc-ui (the one which has been upgraded from 2.5.0 to 2.6.0)

- What is the actual and the expected result using OpenAPI Description (yml or json)?
**Expected**: it should use all the fields from the two objects
**Actual**: only the fields from the parent object are in the openapi documentation

- Provide with a sample code (HelloController) or Test that reproduces the problem

```java
@Builder
@Jacksonized
public record AvailabilityDateRequest(LocalDate date,
                                      @JsonUnwrapped @Delegate AvailabilityRequest availabilityRequest) {

}
```

```java
@Builder
@Jacksonized
public record AvailabilityRequest(List<String> data) {
}
```

**Expected behavior**

In this example, the generated documentation should contain `date` & `data`.
With 2.6.0, it contains only `date`

**Screenshots**
N/A

**Additional context**

**Comment by wingsofovnia** [comment] 2024-09-01 18:56
In my case, I was using `@JsonUnwrapped` in a Kotlin data class and the annotated field just disappeared from the schema. Reverting 2.5.0 fixes the issue.

**Comment by mtsfer** [comment] 2024-09-13 17:36
Apparently, it's not the combination of `@JsonUnwrapped` and `@Delegate`. `@JsonUnwrapped` by itself is not being presented on documentation anymore.

**Comment by bnasslahsen** [comment] 2024-09-21 21:25
This is duplicate of  #2640, which should resolved for the next release.

**Closed by bnasslahsen** 2024-09-21 21:25 UTC
