### ISSUE TITLE
export an offline static documentation 

### ISSUE THREAD

**Issue by rainman-code** [springdoc/springdoc-openapi#1628] opened 2022-04-24 09:36 UTC
how to export an offline static documentation ？thinks

**Comment by bnasslahsen** [comment] 2022-04-24 11:50
This is a duplicate of #706 and not related to `sprindoc-openapi `it self, but to swagger-ui.
You can use https://editor.swagger.io/ if you want export it.

**Closed by bnasslahsen** 2022-04-24 11:50 UTC
