### ISSUE TITLE
Null APIResponse with v1.3.5

### ISSUE THREAD

**Issue by anuragpro** [springdoc/springdoc-openapi#637] opened 2020-05-01 02:34 UTC
https://stackoverflow.com/questions/61529174/null-apiresponse-when-migrating-from-springfox-to-springdoc/61535934#61535934

v1.3.4 seems to be working.

**Comment by bnasslahsen** [comment] 2020-05-01 10:17
@anuragpro, 

 This is duplicate of #630.
 You can test with the fix already deployed on master and which will be released in v1.3.8.

**Closed by bnasslahsen** 2020-05-01 10:17 UTC
