### ISSUE TITLE
Infinite call to ReturnTypeParser.resolveType() with too complex parameterized class

### ISSUE THREAD

**Issue by OlivierRo** [springdoc/springdoc-openapi#2257] opened 2023-06-08 12:28 UTC
**Describe the bug**
I have several REST endpoint using an Object of type "GranuleDTO" (through ResponseEntity<GranuleDTO>, Flux<GranuleDTO> and Mono<GranuleDTO>).
This object is defined with in a relative complex way : 
`public class GranuleDTO<T extends GranuleDTO<T>> implements Comparable<GranuleDTO<T>>`
This permits to declare methods returning T instead of GranuleDTO which in some case avoid using casts (honnestly i don't remember why i had to do this, i just remember i was practicle when i did it).
Anyway, in this case `ReturnTypeParser.resolveType()` is called with `?` and this makes a cyclic call to `ReturnTypeParser.resolveType()`

If i modify class this way, everything is ok :
`public class GranuleDTO<T> implements Comparable<GranuleDTO<T>>`

Spring version is 6.0.9
Springdoc-openapi is 2.1.0

I am updating from springfox because i was fed up with all the bugs ans difficulties to make it functionnal, i am not regretting, your framework is great, good job guys !

**Comment by bnasslahsen** [comment] 2023-07-01 08:36
This a duplicate of https://github.com/springdoc/springdoc-openapi/issues/2271

**Closed by bnasslahsen** 2023-07-01 08:36 UTC
Labels: duplicate
