### ISSUE TITLE
Petstore API still visible on my service's deployed Swagger UI

### ISSUE THREAD

**Issue by oliverlockwood** [springdoc/springdoc-openapi#1064] opened 2021-02-16 15:03 UTC
**Describe the bug**
- If you type the wrong URL, you get the Petstore API on my service's deployed Swagger UI. 😕 

**To Reproduce**
- build a spring-boot 2.3.x service with `springdoc-openapi-ui:1.4.8` dependency and OpenAPI specifications.
- go to http://localhost:18128/swagger-ui.html (in my case, the service is deployed on port 18128)
- this redirects to http://localhost:18128/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config, and looks fine
- if by some mistake you land on http://localhost:18128/swagger-ui/index.html _without_ the `configUrl` query parameter, then you see the Swagger Petstore 1.0.5 APIs, using JSON from https://petstore.swagger.io/v2/swagger.json.  There's no way I can see (without typing the correct URL) to navigate from this window to use the correct Swagger definition.

**Expected behavior**
- Hitting my application's http://localhost:18128/swagger-ui/index.html endpoint should show my application's swagger by default, instead of the example petstore.

I realise that this may just be the default behaviour of the Swagger UI webjar that you pull in, but it still seems weird, so I thought I'd raise an issue to ask if there were any way of changing the default here.

**Comment by bnasslahsen** [comment] 2021-02-16 15:16
@oliverlockwood, 

 This is not a bug.
 But a duplicate of  #714.

 If you want disable it, you can see the appropriate [properties](https://springdoc.org/#properties)

**Closed by bnasslahsen** 2021-02-16 15:16 UTC
