### ISSUE TITLE
"Demo Spring Boot 2 webflux with OpenAPI 3." does not work

### ISSUE THREAD

**Issue by zerg1971** [springdoc/springdoc-openapi#247] opened 2019-12-10 13:47 UTC
URL: https://springdoc-openapi-test-app3-terrific-rabbit.eu-de.mybluemix.net/webjars/swagger-ui/index.html?url=/v3/api-docs&validatorUrl=

```
Whitelabel Error Page
This application has no configured error view, so you are seeing this as a fallback.

Tue Dec 10 13:46:34 UTC 2019
[0b82bfc8] There was an unexpected error (type=Not Found, status=404).

**Comment by springdoc** [comment] 2019-12-11 23:06
duplicate of #239

**Closed by springdoc** 2019-12-11 23:06 UTC
