### ISSUE TITLE
Question: How do I change the default url?

### ISSUE THREAD

**Issue by SR-Lut3t1um** [springdoc/springdoc-openapi#660] opened 2020-05-11 09:26 UTC
If I open swagger using the default link: /swagger-ui/index.html; swagger opens the petstore example, instead of the configuration stored in configUrl=/v3/api-docs/swagger-config.

**Comment by bnasslahsen** [comment] 2020-05-11 11:43
@SR-Lut3t1um, 

 Its duplicate of #43 AND #379

**Closed by bnasslahsen** 2020-05-11 11:43 UTC
