### ISSUE TITLE
required attribute of @Schema has no impact on references

### ISSUE THREAD

**Issue by frankruegamer** [springdoc/springdoc-openapi#430] opened 2020-02-14 11:24 UTC
**Describe the bug**
While primitive types (incl. String) require the `@Schema` and the `required` property, to appear required in the schema, the same doesn't apply for classes,  enums, ... .

**To Reproduce**
I made a simple project which showcases this behaviour:
https://github.com/frankruegamer/springdoc-required-bug

Start the application and observe that the schema looks like the following:
```
components:
  schemas:
    Person:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        pet:
          $ref: '#/components/schemas/Pet'
    Pet:
      required:
      - name
      type: object
      properties:
        name:
          type: string
```

Observe that `pet` is not listed as required while `name` is.

**Expected behavior**
Expected that all primitives and references will be listed as required.

**Workaround**
As a workaround adding a `javax.validation.constraints.NotNull` will correctly set the required status.
`@Schema` already has `required` and `nullable` attributes which should handle all cases, and does so for primitives, so the additional annotation seems cumbersome.

**Comment by bnasslahsen** [comment] 2020-02-15 11:47
Hi, 

 Your issue is duplicate of #156.
 Its a swagger-core issue, that you can follow here:
 - https://github.com/swagger-api/swagger-core/issues/3259

**Closed by bnasslahsen** 2020-02-15 11:47 UTC
