### ISSUE TITLE
Feature: reusable enums

### ISSUE THREAD

**Issue by Sam-Kruglov** [springdoc/springdoc-openapi#995] opened 2020-12-19 14:25 UTC
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

If I use the same enum in 2 requests, I wish the generated spec would generate a [reusable enum](https://swagger.io/docs/specification/data-models/enums/#reuse).

- What is the actual result using OpenAPI Description (yml or json)?

```yaml
paths:
  /products:
    get:
      parameters:
      - in: query
        name: color
        required: true
        type: string
        enum:
          - black
          - white
          - red
          - green
          - blue
      responses:
        '200':
          description: OK
  /products1:
    get:
      parameters:
      - in: query
        name: color
        required: true
        type: string
        enum:
          - black
          - white
          - red
          - green
          - blue
      responses:
        '200':
          description: OK
```

**Describe the solution you'd like**
- A clear and concise description of what you want to happen.

Create a single `Color` enum and reuse it in both requests.

- What is the expected result using OpenAPI Description (yml or json)?

```yaml
paths:
  /products:
    get:
      parameters:
      - in: query
        name: color
        required: true
        schema:
          $ref: '#/components/schemas/Color'
      responses:
        '200':
          description: OK
  /products1:
    get:
      parameters:
      - in: query
        name: color
        required: true
        schema:
          $ref: '#/components/schemas/Color'
      responses:
        '200':
          description: OK
components:
  schemas:
    Color:
      type: string
      enum:
        - black
        - white
        - red
        - green
        - blue
```

**Comment by bnasslahsen** [comment] 2020-12-19 19:21
@Sam-Kruglov, 

 This seems a duplicate of https://github.com/springdoc/springdoc-openapi/issues/232

**Closed by bnasslahsen** 2020-12-19 19:21 UTC

**Comment by Sam-Kruglov** [comment] 2020-12-19 21:08
Thanks! 
I think it would be better if it was the default behavior though.

**Comment by Sam-Kruglov** [comment] 2020-12-20 13:26
Found how to make it the default, just add this static block to any of your classes:
```java
static {
    io.swagger.v3.core.jackson.ModelResolver.enumsAsRef = true;
}
```
