### ISSUE TITLE
Spring Web 6.2.0 cause java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Bricks-Man** [springdoc/springdoc-openapi#2783] opened 2024-11-18 03:54 UTC
**Describe the bug**

- When I use Spring Web 6.2.0 with SpringDoc 2.6.0，will cause `java.lang.NoSuchMethodError: 'void org.springframework.web.method.ControllerAdviceBean.<init>(java.lang.Object)'`

**To Reproduce**

- Spring-boot: 3.3.5
- Springdoc-openapi：org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0
- Spring：6.2.0

**Screenshots**
![image](https://github.com/user-attachments/assets/9d212399-919b-4720-b57d-e1e6070048c8)

![image](https://github.com/user-attachments/assets/348d7dda-f1d9-48d3-8410-4acf1184ca4d)

**Comment by bnasslahsen** [comment] 2024-11-18 11:41
@Bricks-Man,

This is duplicate of  #2771.  It's fixed with 2.7.0-RC1.

**Closed by bnasslahsen** 2024-11-18 11:41 UTC

**Comment by albertus82** [comment] 2024-11-19 09:21
Spring v6.2 was released last week, so is there a planned release date for v2.7.0? Thanks.
