### ISSUE TITLE
Missing Allowable/available values for enums in @ParameterObject

### ISSUE THREAD

**Issue by lv1871codeassistant10** [springdoc/springdoc-openapi#2748] opened 2024-10-06 08:09 UTC
**Describe the bug**
I do not see available values if i use @ParameterObject
![image](https://github.com/user-attachments/assets/1dc09152-5df3-4f5f-a15a-f51517d7935a)

```
@GetMapping("/v2")
    List<Versicherungsdokument.Read> getDokumenteV2(@ParameterObject @Valid CommonPageSearch page,
                                                    @ParameterObject @Valid Versicherungsdokument.Search properties) {
   ...
    }
```

```
public class CommonPageSearch {

    @Schema(description = "Gibt die Richtung der Sortierreihenfolge an. ", defaultValue = "DESC")
    private final SortDirection sortDirection = SortDirection.DESC;
...
}
```

```
public enum SortDirection {
    ASC,
    DESC
}
```

If i use the "normal" way of declare the endpoint i can see the available values:
![image](https://github.com/user-attachments/assets/4e3210d3-a2ea-4c64-86d5-b58c28a63e98)

```
    @GetMapping("/v3")
    List<Versicherungsdokument.Read> getDokumenteV3(@RequestParam(defaultValue = "DESC") SortDirection sortDirection,
                                                    @RequestParam(defaultValue = "BELEGDATUM") D3VersicherungsdokumentBuilder.SortProperties sort,
                                                    @RequestParam @Parameter(required = true) @PageLimits int page,
                                                    @RequestParam @Parameter(required = true) @PageSizeLimits int pageSize,
                                                    @ParameterObject @Valid Versicherungsdokument.Search properties) {
...
    }

```

**To Reproduce**

- What version of spring-boot you are using?
- spring-boot-starter-parent -> 3.3.2
- What modules and versions of springdoc-openapi are you using?
- springdoc-openapi-starter-webmvc-ui -> 2.6.0

**Expected behavior**

If i use the annotation ParameterObject for GetRequests i would like to see the available values for enums

**Comment by bnasslahsen** [comment] 2024-10-06 10:03
@lv1871codeassistant10,

Duplicate of  #2676
Fixed with in the latest SNAPSHOT version, can you test it as well: 2.6.1-SNAPHSOT

**Closed by bnasslahsen** 2024-10-06 10:03 UTC
