### ISSUE TITLE
Javadoc Descriptions Lost When Using @JsonProperty for Property Name Change in springdoc-openapi

### ISSUE THREAD

**Issue by wangxing-git** [springdoc/springdoc-openapi#2438] opened 2023-12-01 08:49 UTC
**Describe the bug**

When using `@JsonProperty` to change the property name, the Javadoc description is lost in the OpenAPI documentation generated by `springdoc-openapi`.

**To Reproduce**

- Spring Boot version: 3.2.0
- springdoc-openapi version: 2.2.0
- Actual and expected result using OpenAPI Description (yml or json): [Include actual and expected OpenAPI descriptions]
- Sample code (TestController or similar) or Test that reproduces the problem: 

```java
@RestController
public class TestController {

    @PostMapping("/springdoc/test")
    public void test(@RequestBody TestRequest request){
    }

    @Data
    static class TestRequest {

        /**
         * aa
         */
        @JsonProperty("b")
        private String a;

    }
}
```

**Expected behavior**

The Javadoc descriptions for properties should be retained in the OpenAPI documentation even when using `@JsonProperty` to change property names.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Additional context**

**Comment by bnasslahsen** [comment] 2023-12-02 21:40
@wangxing-git,

This is a duplicate of https://github.com/springdoc/springdoc-openapi/issues/2315
I have implemented a fix for it.

**Closed by bnasslahsen** 2023-12-02 21:40 UTC
