### ISSUE TITLE
requestBody Description

### ISSUE THREAD

**Issue by nk-rks** [springdoc/springdoc-openapi#816] opened 2020-08-05 12:53 UTC
Am trying to add a description to the requestBody.

Sample code:
```
Public void func(@Valid @Parameter(description = "REQUEST BODY DESCRIPTION") @RequestBody String) throws Exception {
   // DO SOMETHING
}
````

Results:
```
"requestBody" : {
      "content" : {
            "application/json" : {
                "schema" : {
                    "type" : "string",
                    "description" : "REQUEST BODY DESCRIPTION"
                  }
            }
      }
}
```

Expected results:
```
"requestBody" : {
    "description" : "REQUEST BODY DESCRIPTION",
      "content" : {
            "application/json" : {
                "schema" : {
                    "type" : "string"
                  }
            }
      }
}
```

OpenAPI supports a description for the requestBody , yet SpringDoc's @RequestBody annotation does not have a description param.

spring-boot: 2.0.3
springdoc-openapi: 1.4.3

**Comment by debargharoy** [comment] 2020-08-06 11:15
Duplicate of #782 
Check [comment](https://github.com/springdoc/springdoc-openapi/issues/782#issuecomment-657491343)

**Comment by bnasslahsen** [comment] 2020-08-06 18:59
Exactly @debargharoy, 

 @nk-rks, the straightforward way for your example, is to use the description of the `@RequestBody` annotation:

```java
	public void func(@Valid @RequestBody(description = "REQUEST BODY DESCRIPTION") String) throws Exception {
		// DO SOMETHING
	}
```

**Closed by bnasslahsen** 2020-08-06 18:59 UTC
