### ISSUE TITLE
Error on swagger-ui: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by KirillNNRUS** [springdoc/springdoc-openapi#1137] opened 2021-04-11 09:14 UTC
Can you help me with my RestApi endpoint?
Swager doesn't work(
What I am do wrong?
https://github.com/KirillNNRUS/demo

**Comment by bnasslahsen** [comment] 2021-04-11 13:25
@KirillNNRUS, 

 It's a duplicate of:  #1130

 As answered before, this looks to be an issue on the swagger-ui.
 I have logged an issue on the swagger-ui project: https://github.com/swagger-api/swagger-ui/issues/7160

You have two workarounds: 

1. Simply use: `@ParameterObject User user`: You can add the description using `@Schema` annotation, on the class attributes
2. Don't use content, for simple parameters: And this is a sample working code.

```java
@Parameter(name = "someEnums", in = QUERY, description = "SomeEum decs", array = @ArraySchema(schema = @Schema(type = "string", allowableValues = {"FIRST", "SECOND"})))
@Parameter(name = "textSet", in = QUERY, description = "First decs", array = @ArraySchema(schema = @Schema(type = "string")))
@Parameter(name = "someText", in = QUERY, description = "Second decs", schema = @Schema(type = "string"))
```

**Closed by bnasslahsen** 2021-04-11 13:25 UTC
