### ISSUE TITLE
Wrong operationid generated

### ISSUE THREAD

**Issue by tezine** [springdoc/springdoc-openapi#675] opened 2020-05-18 19:32 UTC
Hello, 
This bug is probably the same as bug [96](https://github.com/springdoc/springdoc-openapi/issues/96). 
OperationID continues to be generated with a suffix, even when there's no other method with the same operationid in the same class. 

This issue is easy to reproduce:  
1. Create two controllers classes. 
1. Create one method with the same name in both classes. 
1. http://yoursite/v3/api-docs will produce one operationid correct and the other will have the 1 suffix. 

Ex: 
    MyFirstClass.java:
```java
    @Operation(operationId = "save")
    @PostMapping(path = "/")
    @ApiResponse(responseCode = "200", description = "Success")
    public ResponseEntity save(@RequestBody String request) {
      return null;
    }
```
    MySecondClass.java:
```java
    @Operation(operationId = "save")
    @PostMapping(path = "/")
    @ApiResponse(responseCode = "200", description = "Success")
    public ResponseEntity save(@RequestBody String request) {
      return null;
    }
```

After generation, one method will have the correct operationid (save), but the other one will have a wrong operationid(save_1)
This bug is happening with SpringDoc 1.3.0, SpringBoot 2.2.6, openJDK 11 64bits on Windows.

**Comment by bnasslahsen** [comment] 2020-05-18 19:43
Hi @tezine, 

 This is not a bug, but a normal behaviour as we don't want to generate incorrect spec:
 - The operationId should be unique
 - When it not the case (for example in case of polymorphism), springdoc generates a unique id

If you have two operations with the same id, your spec will be incorrect.

Please make sure you use the last stable version: v1.3.9 indeed.

**Closed by bnasslahsen** 2020-05-18 19:43 UTC

**Comment by tezine** [comment] 2020-05-19 10:27
> Hi @tezine,
> 
> This is not a bug, but a normal behaviour as we don't want to generate incorrect spec:
> 
> * The operationId should be unique
> * When it not the case (for example in case of polymorphism), springdoc generates a unique id
> 
> If you have two operations with the same id, your spec will be incorrect.
> 
> Please make sure you use the last stable version: v1.3.9 indeed.

Thank you @bnasslahsen for the quick response. It just think it doesn't make any sense. For instance, I'm generating REST calls to Angular in typescript. In this situation, I have two calls: 

```typescript
MyFirstClassService.save() and MySecondClassService.save_1(). //It doesn't make sense. 
```

**Comment by bnasslahsen** [comment] 2020-05-19 10:40
@tezine, 

 I invite you to read the spec: https://swagger.io/docs/specification/paths-and-operations/

> operationId is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in your API.

**Comment by jdbranham** [comment] 2020-08-04 05:15
In my case, I've got lots of rest controllers that extend a generalized abstract crud controller.

Rather than generating operations with `_n` after, it would be cool if we could use a class level annotation to do a pre/post fix on the generated operation id. Otherwise I've got to override all the superclass methods and re-add all the annotations in the subclass.
Is that something PR worthy?

**Comment by jdbranham** [comment] 2020-08-04 06:10
Nvm - I just realized there is an `OperationCustomizer` class while browsing the source code - 

https://github.com/springdoc/springdoc-openapi/blob/2da39aae2976ef1cc888e5696caf763fb6f05fcf/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L641

I was able to provide a bean and customize my generated names =]  

Thanks for a great project!!

```
@Bean
public OperationCustomizer operationIdCustomizer() {
  OperationCustomizer c = new OperationCustomizer() {
    @Override
    public Operation customize(Operation operation, HandlerMethod handlerMethod) {
	Class<?> superClazz = handlerMethod.getBeanType().getSuperclass();
	if (Objects.nonNull(superClazz) && superClazz.isAssignableFrom(CrudController.class)) {
		String beanName = handlerMethod.getBeanType().getSimpleName();
		operation.setOperationId(String.format("%s_%s", beanName, handlerMethod.getMethod().getName()));
	}
	return operation;
    }
  };
  return c;
}
```

**Comment by Angi2412** [comment] 2022-12-21 10:28
This issue is still present and not documented. This workaround seems not be up to date anymore. Is there any updated solution for the problem?

**Comment by kozla13** [comment] 2024-10-08 20:10
How can i handle 2 paths 

	@GetMapping({"/app-statistic", "/members/app-statistic"}) //other security rules
	public AppStatistic getAppStatistic() {

}

**Comment by bnasslahsen** [comment] 2024-10-08 20:39
@kozla13 ,

You will have unique operation ids generated by default.
If you want use your custom operation ids, use `OperationCustomizer`.
